import { pgTable, text, integer, doublePrecision, jsonb, index, boolean } from 'drizzle-orm/pg-core'

export const phone = pgTable('phone', {
  id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
  slug: text('slug'),
  name: text('name'),
  description: text('description'),
  android_auto: text('android_auto'),
  asia_network: jsonb('asia_network'),
  bluetooth: jsonb('bluetooth'),
  brand: text('brand'),
  browser: jsonb('browser'),
  calendar: boolean('calendar'),
  camera: jsonb('camera'),
  category: jsonb('category'),
  dual_sim: jsonb('dual_sim'),
  email: jsonb('email'),
  esim: jsonb('esim'),
  europe_network: jsonb('europe_network'),
  featured: boolean('featured').default(false),
  gps_navigation: jsonb('gps_navigation'),
  group_text_mms: jsonb('group_text_mms'),
  headphone_jack: jsonb('headphone_jack'),
  hotspot_tethering: jsonb('hotspot_tethering'),
  image: text('image'),
  link: text('link'),
  network: jsonb('network'),
  nfc_support: text('nfc_support'),
  operating_system: jsonb('operating_system'),
  podcasts_music: jsonb('podcasts_music'),
  price: text('price'),
  rating: doublePrecision('rating'),
  region: jsonb('region'),
  removable_battery: jsonb('removable_battery'),
  rideshare: jsonb('rideshare'),
  rugged: jsonb('rugged'),
  screen_size_inches: doublePrecision('screen_size_inches'),
  screen_type: jsonb('screen_type'),
  sd_cards: jsonb('sd_cards'),
  shape: jsonb('shape'),
  signal_app: jsonb('signal_app'),
  sim_type: jsonb('sim_type'),
  sold_unlocked: jsonb('sold_unlocked'),
  spotify: jsonb('spotify'),
  support_and_updates: jsonb('support_and_updates'),
  supported_networks: jsonb('supported_networks'),
  t9_keyboard: jsonb('t9_keyboard'),
  touchscreen: text('touchscreen'),
  two_factor_auth: jsonb('two_factor_auth'),
  usb_type: jsonb('usb_type'),
  voice_to_text: jsonb('voice_to_text'),
  volte: boolean('volte'),
  whatsapp: jsonb('whatsapp'),
  wifi_calling: jsonb('wifi_calling'),
}, (table) => ({
  idIndex: index('dump_id_index').on(table.id),
}))

export type Phone = typeof phone.$inferSelect
export type InsertPhone = typeof phone.$inferInsert