export interface Phone {
  id: number
  name: string | null
  brand: string | null
  link: string | null
  price: string | null
  support_and_updates: string | null
  category: string | null
  network: string | null
  G_4G_3G_2G: string | null
  volte: string | null
  rideshare: string | null
  gps_navigation: string | null
  shape: string | null
  group_text_mms: string | null
  removable_battery: string | null
  operating_system: string | null
  hotspot_tethering: string | null
  browser: string | null
  wifi_calling: string | null
  whatsapp: string | null
  sd_cards: string | null
  FA: string | null
  spotify: string | null
  email: string | null
  voice_to_text: string | null
  t9_keyboard: string | null
  usb_type: string | null
  headphone_jack: string | null
  signal_app: string | null
  camera: string | null
  calendar: string | null
  screen_size_inches: string | null
  screen_type: string | null
  sim_type: string | null
  sold_unlocked: string | null
  dual_sim: string | null
  podcasts_music: string | null
  rugged: string | null
  bluetooth: string | null
  image: string | null
  europe_network: string | null
  touchscreen: string | null
  android_auto: string | null
  region: string | null
  asia_network: string | null
  nfc_support: string | null
  esim: string | null
  rating: number | null
}